jobs:
  include:
  - name: test
    language: node_js
    node_js: 13
    install:
    - yarn install && cd functions && npm install
    script:
    - npm test
  - name: android
    os: linux
    if: false # tag IS blank
    language: android
    dist: trusty
    node_js: 13
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-28.0.3
      - android-27
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    cache:
      directories:
      - node_modules/
    before_install:
    - nvm install 13
    - yes | sdkmanager tools > /dev/null
    - yes | sdkmanager --licenses > /dev/null
    - echo {} > cordova-app/build.json
    - if [ "$TRAVIS_PULL_REQUEST" == false ]; then openssl aes-256-cbc -K $encrypted_24a643539195_key
      -iv $encrypted_24a643539195_iv -in cordova-app/secrets.tar.enc -out cordova-app/secrets.tar
      -d && cd cordova-app && tar xvf secrets.tar && cd ..; fi
    install:
    - npm install
    script:
    - npm test -- --coverage
    - npm run build
    - npm run build:android
    before_deploy:
    - git config --local user.name "Geovation from Travis"
    - git config --local user.email "info@geovation.uk"
    - export ORIGINAL_TAG=$TRAVIS_TAG
    - export TRAVIS_TAG=$(date +'%Y%m%d%H%M%S')-Android-$TRAVIS_BUILD_NUMBER-$(git log --format=%h -1)
    - git tag $TRAVIS_TAG
    - gem install fastlane -NV
    - export TRAVIS_TAG=$ORIGINAL_TAG
    - echo $TRAVIS_TAG

    env:
    - secure: "CLic/Dhru12PIvTZrBKQIV7YXiiH216Nd0ku0t89sZ+QHVeuuyJZaYPEdP/eFtl9aoN8CEazIkFOgjYjJqhkN6ilYPp3IaQ2s8lbu+gzCi3jcBDGCxwxUGipFiCSZWYHx4xwVg4SPi9mmJYjsHMSsh65meLtJE6hQ5TBcFbCyjt/b5Be2Y3n3w5fZvrBl94hrVxjI1rv3R2a1/PACIfuArvFtEO2FQl+3mq565qyNVAuY2282PocDMY7qp896HUGefBjByoPb21oOQhbnStLBga1nmNjPqYGZG6KIkmTz52yjLRSwXCPwrKHWDlzarGoIGF0EpHF7FvvZnVN8SA0hx4hTaD43ewsNhORg08dGBvFDCWgsQn7XOgheJT6KXHx8kBjWGLEDBssQTh79siGQe0IGJgUixTht1c+OqXOWhHRoD+Cyz1Wnwc0APOS39vT+Nz3oPS1L7UbrcWq8Stk/A/ZDfpxCz55UJ07KbXzyy/U6/0XupMUG/k5hY8HSET9GhLxsVpeMysrIAszOa0ffJDfr+52VvnWWVlCu/DYvbmk3aOF1g/Ke+Ar0p/ZTFgFx5pobaAkcBGkXwRke5HJEFM1bmMvxUILJp3NANeqsZDJHLY57T/2PM1S0dj+PdaFj3iQ7y/7YjS3s+c0YmEZFpx3zOHZDh1X5sjMTenr8Bw="


    deploy:
    - provider: releases
      token:
        secure: X29iYfl6eW1lGrzk2B8VlZsYi0iCeLE18ZCp23LUPuLqGWEVne/SQf/wwf0EmMoBRBG4X+cs/xFzraA4wdpMXmwJjJo+XvH9SFIw2jfVKwHHwpWnLGcq/9mK14p4tUB5TxhCboH67UqmZqqV2MJ9cuJeEQSxaY0Dh1pOxJruftpXp+mKjoLB2hEhY82Yu+NA0k0JwSdCfb0opPIXelqNmrjgwuLpQgnvKjMK9Mu9meGFwdOYa8dq3oMetLknTcro6IX2DMuxCYR7qUq1BcnA+1vnu/UsvZyRy/25I890WK3B0uVs6NiIwmNNrctxViOmBCo6wInLxqfTKBgHB2DAHJavlQZMMaj/7o81+YF4Egpi7t9XE7BR1DPWxMsDxTHHWIcgWsr25Yk7aFAH+3yEDexqxSscYQvMM5ISsX8ofvFCLRYwyAAjWib04d1SoEKTfrua9pL/TRx0J1Y7lJ21wnj4kbzmstuCvDLxt9QzEY9WXC/AQnkYz1CpuR7QIGZKxyYU/7aZbLjQfAaQp0GnAHxiwwAS9ofIovEh18Q2r1BGIpCnI4Zosfq/5eTY9dz+JCpKvOr52HqT+up7OiPbfIbtmXYS38Go/MMOLlMnRN6bvbQQHc2Al8S0c29WZtpOfkRcqbpx+fcZ80UexEouCKkmrIROXEWruZDMTBMcD2k=
      file: cordova-app/platforms/android/app/build/outputs/apk/release/app-release.apk

    - provider: script
      script: npm run beta:android

  - os: linux
    if: false # tag =~ /^release-[0-9]+.[0-9]+.[0-9]+$/
    language: node_js
    dist: trusty
    node_js: 13

    cache:
      directories:
        - node_modules/
    before_install:
      - nvm install 13
    install:
      - npm install
    script:
      - npm test -- --coverage
      - npm run build
    before_deploy:
      - pushd functions && npm install && popd
      - git config --local user.name "Geovation from Travis"
      - git config --local user.email "info@geovation.uk"
      - export ORIGINAL_TAG=$TRAVIS_TAG
      - export TRAVIS_TAG=$(date +'%Y%m%d%H%M%S')-Android-$TRAVIS_BUILD_NUMBER-$(git log --format=%h -1)
      - git tag $TRAVIS_TAG
      - export TRAVIS_TAG=$ORIGINAL_TAG
      - echo $TRAVIS_TAG

    env:
      - secure: "CLic/Dhru12PIvTZrBKQIV7YXiiH216Nd0ku0t89sZ+QHVeuuyJZaYPEdP/eFtl9aoN8CEazIkFOgjYjJqhkN6ilYPp3IaQ2s8lbu+gzCi3jcBDGCxwxUGipFiCSZWYHx4xwVg4SPi9mmJYjsHMSsh65meLtJE6hQ5TBcFbCyjt/b5Be2Y3n3w5fZvrBl94hrVxjI1rv3R2a1/PACIfuArvFtEO2FQl+3mq565qyNVAuY2282PocDMY7qp896HUGefBjByoPb21oOQhbnStLBga1nmNjPqYGZG6KIkmTz52yjLRSwXCPwrKHWDlzarGoIGF0EpHF7FvvZnVN8SA0hx4hTaD43ewsNhORg08dGBvFDCWgsQn7XOgheJT6KXHx8kBjWGLEDBssQTh79siGQe0IGJgUixTht1c+OqXOWhHRoD+Cyz1Wnwc0APOS39vT+Nz3oPS1L7UbrcWq8Stk/A/ZDfpxCz55UJ07KbXzyy/U6/0XupMUG/k5hY8HSET9GhLxsVpeMysrIAszOa0ffJDfr+52VvnWWVlCu/DYvbmk3aOF1g/Ke+Ar0p/ZTFgFx5pobaAkcBGkXwRke5HJEFM1bmMvxUILJp3NANeqsZDJHLY57T/2PM1S0dj+PdaFj3iQ7y/7YjS3s+c0YmEZFpx3zOHZDh1X5sjMTenr8Bw="

    deploy:
      - provider: firebase
        on:
          tags: true
          all_branches: true
          condition: "$TRAVIS_TAG =~ ^release.*$"
        token:
          secure: B4kTpVinIjqF/QSzpsgL9XgKu3o0ZfCbGQvVLj48HLzlYjN3u4Wq2IRdeoLlo/ais8dx4pNhmAo8GWCrbnQvv8DfJ4RzKReHI6giXndPGvpl5IjDFnQyewMBT4eJhj4HkNWt6erWU+joyYVAJ8Mot2FIhKKD52JXuahQAvRvLZO9sL3kIxblsZC8LvdzNqIvKv27m4SZd+D4ZA8RI9T7lMjAl8k4SSzB+pGcs/rhcPm8lxlCU2C5Owu4rsoM0nTzX2RKbVykCM/tpUxXSZAO0DC1vIt7OhQYqv/Z690Db7+1jbmaIs4+O3SSWxDA6I2TJWg5+qgYmrABUA06G+nCK8RicRr1+91RdOXKpi6XXS+nSY9f8UfeeCXabfj+2lcHU6LlEK2qwNwVpiw6ahOAikWo27RGM0ZSj2j4k5kE/vlnV8wQ8gW+X2zTDVPnyGi/NXvGiAJvELrN+C5v/orIruoVvdetACgXtIjIxlyOYlxVEMFXnyl6phZvi1WS+9oFgJeXyj/zxtmTCQFvM1wJ+VqEjnwyy5bCisZwkdyhej2aXvaYXjRmG3SPX1DqwsnLOob4lngFp0KCw1f4BgpycqsPnVcw8PK/sGJ+Gj8ehBkmS9FuOgi9vHSIJxdTVcOExLaYu2VjhRx1C+MLsK9O14Iq60YL59tXLK9WHOEmeis=

    # build the iOS app in debug mode
  - name: ios:dev
    os: osx
    if: false # type == pull_request AND tag IS blank
    language: objective-c
    osx_image: xcode12.2
    node_js: 14
    env:
    - secure: jfdXsl7ajV/xQNW47p1yyEKDkMfxMRqOQE6U/vmGTKA78SLwvCYYjQUksXh8Tupoiz71mDF5qzUL7Y1tuKONlFeMOh4Qmkcyom33+lzPUeiF3lQpPocLNMP2Y77HnuKQiPb9dpdPAzpAHoVrETTSW+XX03qzb2okojx80t2QDUlhieZ6qVTWWtpaRG3P+nv8Ms/cBMBRlOJ+dLLMa6o1rOOlYJnr2ARwJfvezY0S/OvDx+lX4C4MnRp3emCLK+2tzAPrZ3kNn/9jYmgdIybDSqMpCiPfSF3vrOfOakpefVINLbafI1qJMTbnL1ANwFK/MjgMLyR0HRnrvVCLv9rIk8oie/Vr+OPxssAzqmdOcey4hVCNd15mxf1/ZtbnXQpmt4GF02NggrGtVSd9vIqws+EhKl+X55NFnM/BjnagUFjKWl4Kl2yunYwFkywbARbQe6RNzi7mOzwizoduLxPboGcOPoREjrCxAaefsXtlxJZVyuYW+9ylIMDsrr/1xD1nPof8Wv+HqIgDWdBkK1FWiyJvYBBEyQY5gdm9fRPhorO45BZ0fAMnC8JhsnajPFnmuRR88VQHLNW/XDPgTM+FADNMZcFMj+Z1hu2V0eDXebFILthvRU5Q82MLMHUPEhYc/h82wy2+SWD3m5nDmja/W52lWNO+C8jp0O7Zt177V08=
    - secure: "CLic/Dhru12PIvTZrBKQIV7YXiiH216Nd0ku0t89sZ+QHVeuuyJZaYPEdP/eFtl9aoN8CEazIkFOgjYjJqhkN6ilYPp3IaQ2s8lbu+gzCi3jcBDGCxwxUGipFiCSZWYHx4xwVg4SPi9mmJYjsHMSsh65meLtJE6hQ5TBcFbCyjt/b5Be2Y3n3w5fZvrBl94hrVxjI1rv3R2a1/PACIfuArvFtEO2FQl+3mq565qyNVAuY2282PocDMY7qp896HUGefBjByoPb21oOQhbnStLBga1nmNjPqYGZG6KIkmTz52yjLRSwXCPwrKHWDlzarGoIGF0EpHF7FvvZnVN8SA0hx4hTaD43ewsNhORg08dGBvFDCWgsQn7XOgheJT6KXHx8kBjWGLEDBssQTh79siGQe0IGJgUixTht1c+OqXOWhHRoD+Cyz1Wnwc0APOS39vT+Nz3oPS1L7UbrcWq8Stk/A/ZDfpxCz55UJ07KbXzyy/U6/0XupMUG/k5hY8HSET9GhLxsVpeMysrIAszOa0ffJDfr+52VvnWWVlCu/DYvbmk3aOF1g/Ke+Ar0p/ZTFgFx5pobaAkcBGkXwRke5HJEFM1bmMvxUILJp3NANeqsZDJHLY57T/2PM1S0dj+PdaFj3iQ7y/7YjS3s+c0YmEZFpx3zOHZDh1X5sjMTenr8Bw="
    cache:
      directories:
      - node_modules/
    before_install:
    - nvm install 14
    - echo {} > cordova-app/build.json
    - pod repo update
    script:
    - npm run build
    - npm run build:ios:dev
    install:
    - npm install
    - npm install ios-deploy

    # build the iOS app for a device, requires code signing, so don't run on PRS
    # (we need to decrypt the required keys)
  - name: ios:prod
    os: osx
    if: type != pull_request AND tag IS blank
    branches:
      only:
      - master
    language: objective-c
    osx_image: xcode12.2
    node_js: 14
    env:
    - secure: jfdXsl7ajV/xQNW47p1yyEKDkMfxMRqOQE6U/vmGTKA78SLwvCYYjQUksXh8Tupoiz71mDF5qzUL7Y1tuKONlFeMOh4Qmkcyom33+lzPUeiF3lQpPocLNMP2Y77HnuKQiPb9dpdPAzpAHoVrETTSW+XX03qzb2okojx80t2QDUlhieZ6qVTWWtpaRG3P+nv8Ms/cBMBRlOJ+dLLMa6o1rOOlYJnr2ARwJfvezY0S/OvDx+lX4C4MnRp3emCLK+2tzAPrZ3kNn/9jYmgdIybDSqMpCiPfSF3vrOfOakpefVINLbafI1qJMTbnL1ANwFK/MjgMLyR0HRnrvVCLv9rIk8oie/Vr+OPxssAzqmdOcey4hVCNd15mxf1/ZtbnXQpmt4GF02NggrGtVSd9vIqws+EhKl+X55NFnM/BjnagUFjKWl4Kl2yunYwFkywbARbQe6RNzi7mOzwizoduLxPboGcOPoREjrCxAaefsXtlxJZVyuYW+9ylIMDsrr/1xD1nPof8Wv+HqIgDWdBkK1FWiyJvYBBEyQY5gdm9fRPhorO45BZ0fAMnC8JhsnajPFnmuRR88VQHLNW/XDPgTM+FADNMZcFMj+Z1hu2V0eDXebFILthvRU5Q82MLMHUPEhYc/h82wy2+SWD3m5nDmja/W52lWNO+C8jp0O7Zt177V08=
    - secure: "CLic/Dhru12PIvTZrBKQIV7YXiiH216Nd0ku0t89sZ+QHVeuuyJZaYPEdP/eFtl9aoN8CEazIkFOgjYjJqhkN6ilYPp3IaQ2s8lbu+gzCi3jcBDGCxwxUGipFiCSZWYHx4xwVg4SPi9mmJYjsHMSsh65meLtJE6hQ5TBcFbCyjt/b5Be2Y3n3w5fZvrBl94hrVxjI1rv3R2a1/PACIfuArvFtEO2FQl+3mq565qyNVAuY2282PocDMY7qp896HUGefBjByoPb21oOQhbnStLBga1nmNjPqYGZG6KIkmTz52yjLRSwXCPwrKHWDlzarGoIGF0EpHF7FvvZnVN8SA0hx4hTaD43ewsNhORg08dGBvFDCWgsQn7XOgheJT6KXHx8kBjWGLEDBssQTh79siGQe0IGJgUixTht1c+OqXOWhHRoD+Cyz1Wnwc0APOS39vT+Nz3oPS1L7UbrcWq8Stk/A/ZDfpxCz55UJ07KbXzyy/U6/0XupMUG/k5hY8HSET9GhLxsVpeMysrIAszOa0ffJDfr+52VvnWWVlCu/DYvbmk3aOF1g/Ke+Ar0p/ZTFgFx5pobaAkcBGkXwRke5HJEFM1bmMvxUILJp3NANeqsZDJHLY57T/2PM1S0dj+PdaFj3iQ7y/7YjS3s+c0YmEZFpx3zOHZDh1X5sjMTenr8Bw="
    cache:
      directories:
      - node_modules/
    before_install:
    - nvm install 14
    - echo {} > cordova-app/build.json
    - if [ "$TRAVIS_PULL_REQUEST" == false ]; then openssl aes-256-cbc -K $encrypted_24a643539195_key
      -iv $encrypted_24a643539195_iv -in cordova-app/secrets.tar.enc -out cordova-app/secrets.tar
      -d && cd cordova-app && tar xvf secrets.tar && cd ..; fi
    - if [ "$TRAVIS_PULL_REQUEST" == false ]; then ./scripts/add-key.sh; fi
    - pod repo update
    script:
    - npm run build
    - npm run build:ios
    install:
    - npm install
    - npm install ios-deploy
    before_deploy:
    - git config --local user.name "Geovation from Travis"
    - git config --local user.email "info@geovation.uk"
    - export TRAVIS_TAG=$(date +'%Y%m%d%H%M%S')-iPhone-$TRAVIS_BUILD_NUMBER-$(git log --format=%h -1)
    - git tag $TRAVIS_TAG
    - gem install fastlane -NV
    deploy:
      - provider: releases
        token:
          secure: X29iYfl6eW1lGrzk2B8VlZsYi0iCeLE18ZCp23LUPuLqGWEVne/SQf/wwf0EmMoBRBG4X+cs/xFzraA4wdpMXmwJjJo+XvH9SFIw2jfVKwHHwpWnLGcq/9mK14p4tUB5TxhCboH67UqmZqqV2MJ9cuJeEQSxaY0Dh1pOxJruftpXp+mKjoLB2hEhY82Yu+NA0k0JwSdCfb0opPIXelqNmrjgwuLpQgnvKjMK9Mu9meGFwdOYa8dq3oMetLknTcro6IX2DMuxCYR7qUq1BcnA+1vnu/UsvZyRy/25I890WK3B0uVs6NiIwmNNrctxViOmBCo6wInLxqfTKBgHB2DAHJavlQZMMaj/7o81+YF4Egpi7t9XE7BR1DPWxMsDxTHHWIcgWsr25Yk7aFAH+3yEDexqxSscYQvMM5ISsX8ofvFCLRYwyAAjWib04d1SoEKTfrua9pL/TRx0J1Y7lJ21wnj4kbzmstuCvDLxt9QzEY9WXC/AQnkYz1CpuR7QIGZKxyYU/7aZbLjQfAaQp0GnAHxiwwAS9ofIovEh18Q2r1BGIpCnI4Zosfq/5eTY9dz+JCpKvOr52HqT+up7OiPbfIbtmXYS38Go/MMOLlMnRN6bvbQQHc2Al8S0c29WZtpOfkRcqbpx+fcZ80UexEouCKkmrIROXEWruZDMTBMcD2k=
        file: "cordova-app/platforms/ios/build/device/Plastic\ Patrol.ipa"

      - provider: script
        script: npm run beta:ios
