name: Deploy to testflight

on:
  push:
    branches:
      - "master"


jobs:
  ios:
    runs-on: macos-latest
    # fetch the code
    steps:
      - uses: actions/checkout@v2

# TODO: auto bump version: need to make it happen only once (It is happening also in deploy-to-dev.yml) 

    # TODO: build react
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: yarn
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn
      - run: yarn test
      - run: yarn build

# decrypt files
      - run: openssl enc -d -aes-256-cbc -in cordova-app/secrets.tar.encrypted -out cordova-app/secrets.tar -k ${{ secrets.ENC_PASSWORD }} -md sha512
      - run: pushd cordova-app && tar xvf secrets.tar && popd
          
# build ios and sign
      - run: ./scripts/add-key-github.sh
      - run: yarn build:ios
        
# it will contain the ios image too 
      - run: mkdir -p artifacts/react-build
      - run: cp -a build/ artifacts/react-build
      - run: cp -a cordova-app/platforms/ios/build/device/ artifacts/ios-build
      - uses: actions/upload-artifact@v2
        with:
          name: react-build
          path: artifacts/react-build

# TODO: testflight
