name: Deploy to testflight

on:
  push:
    branches:
      - "master"


jobs:
  ios:
    runs-on: macos-latest
    # fetch the code
    steps:
      - uses: actions/checkout@v2

# TODO: auto bump version: need to make it happen only once (It is happening also in deploy-to-dev.yml) 

    # TODO: build react
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: yarn
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn
      - run: yarn test
      - run: yarn build

      - uses: actions/download-artifact@v2
        with:
          name: react-build
          path: build
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build

# TODO: decrypt files
# TODO: build ios and sign
# TODO: testflight
