name: Run tests against commit

on: [pull_request]

jobs:
  branch-deploy:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('yarn.lock') }}

      - name: yarn
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: cypress tests
        run: |
          yarn start &
          $(npm bin)/cypress verify &
          $(npm bin)/wait-on --timeout 120000 http-get://localhost:3000

          yarn run:cypress
