name: Run tests against commit

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Cypress run
        uses: cypress-io/github-action@v1
